approve_by_comment: true
approve_regex: '^LGTM\s\w'
reject_regex: '^REJECT'
reject_value: -1
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: admins
        required: 1
        members:
            - ccorral
            - dloyst
            - dslee393
            - the-gingerbread-man
        conditions:
            branches:
                - master